dataset: torch/cifar100
num_classes: 100
img_size: 32
mean:
    - 0.5071
    - 0.4867
    - 0.4408
std:
    - 0.2675
    - 0.2565
    - 0.2761
crop_pct: 1.0
scale:
    - 0.8
    - 1.0
interpolation: bicubic
train_interpolation: random
aa: rand-m9-mstd0.5-inc1
mixup: 0.8
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_mode: batch
mixup_switch_prob: 0.5
cutmix: 1.0
reprob: 0.25
remode: pixel
amp: True
batch_size: 256
lr: 6e-4
min_lr: 1e-5
sched: cosine
weight_decay: 6e-2
epochs: 400
cooldown_epochs: 10
warmup_epochs: 10
warmup_lr: 0.000001
opt: adamw
smoothing: 0.1
workers: 8
ws_mode: "PerChlMPLn"
wq_enable: False
wq_mode: "LSQ"
wq_bitw: 1
# wq_pos: 1
# wq_neg: -1
aq_enable: False
aq_mode: "LSQ"
aq_bitw: 1
# aq_pos: 1
# aq_neg: -1
resq_enable: False
resq_mode: "LSQ"
resq_bitw: 1
# resq_pos: 1
# resq_neg: -1%
