dataset: torch/image_folder
num_classes: 200
train_split: train
val_split: valid
img_size: 64
mean:
    - 0.485
    - 0.456
    - 0.406
std:
    - 0.229
    - 0.224
    - 0.225
crop_pct: 1.0
scale:
    - 0.8
    - 1.0
# initial_checkpoint: /home/xts/code/MySparsity/Ternary-ViT/output/train/20231015-165356-tinyimagenet_mobilenetv2-64/model_best.pth.tar
initial_checkpoint: /home/xts/code/MySparsity/Ternary-ViT/output/train/mbv2_w8a3/w8a3.pth.tar
interpolation: bicubic
train_interpolation: random
aa: rand-m9-mstd0.5-inc1
mixup: 0.8
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_mode: batch
mixup_switch_prob: 0.5
cutmix: 1.0
reprob: 0.25
remode: pixel
amp: True
batch_size: 32
lr: 55e-5
min_lr: 1e-5
sched: cosine
weight_decay: 6e-2
epochs: 200
cooldown_epochs: 10
warmup_epochs: 25
warmup_lr: 0.00001
opt: adamw
smoothing: 0.1
workers: 64
wq_enable: True
wq_mode: "LSQ"
wq_bitw: 3
wq_per_channel: True
wq_asym: False
aq_enable: True
aq_mode: "LSQ"
aq_bitw: 3
aq_asym: True
resq_enable: True
resq_mode: "LSQ"
resq_bitw: 8
resq_asym: True
qmodules: 
  - features.0.0;wq:bit:8;aq:bit:8
  - features.1.conv.0;wq:bit:8
  - features.1.conv.3
  - features.2.conv.0
  - features.2.conv.3;wq:bit:8
  - features.2.conv.6
  - features.3.conv.0
  - features.3.conv.3;wq:bit:8
  - features.3.conv.6
  - features.4.conv.0
  - features.4.conv.3;wq:bit:8
  - features.4.conv.6
  - features.5.conv.0
  - features.5.conv.3;wq:bit:8
  - features.5.conv.6
  - features.6.conv.0
  - features.6.conv.3;wq:bit:8
  - features.6.conv.6
  - features.7.conv.0
  - features.7.conv.3;wq:bit:8
  - features.7.conv.6
  - features.8.conv.0
  - features.8.conv.3;wq:bit:8
  - features.8.conv.6
  - features.9.conv.0
  - features.9.conv.3;wq:bit:8
  - features.9.conv.6
  - features.10.conv.0
  - features.10.conv.3;wq:bit:8
  - features.10.conv.6
  - features.11.conv.0
  - features.11.conv.3;wq:bit:8
  - features.11.conv.6
  - features.12.conv.0
  - features.12.conv.3;wq:bit:8
  - features.12.conv.6
  - features.13.conv.0
  - features.13.conv.3;wq:bit:8
  - features.13.conv.6
  - features.14.conv.0
  - features.14.conv.3;wq:bit:8
  - features.14.conv.6
  - features.15.conv.0
  - features.15.conv.3;wq:bit:8
  - features.15.conv.6
  - features.16.conv.0
  - features.16.conv.3;wq:bit:8
  - features.16.conv.6
  - features.17.conv.0
  - features.17.conv.3;wq:bit:8
  - features.17.conv.6
  - classifier.1;wq:bit:8;aq:bit:8
  # - features.0.1
  # - features.1.conv.1
  # - features.1.conv.4
  # - features.2.conv.1
  # - features.2.conv.4
  # - features.2.conv.7
  # - features.3.conv.1
  # - features.3.conv.4
  # - features.3.conv.7
  # - features.4.conv.1
  # - features.4.conv.4
  # - features.4.conv.7
  # - features.5.conv.1
  # - features.5.conv.4
  # - features.5.conv.7
  # - features.6.conv.1
  # - features.6.conv.4
  # - features.6.conv.7
  # - features.7.conv.1
  # - features.7.conv.4
  # - features.7.conv.7
  # - features.8.conv.1
  # - features.8.conv.4
  # - features.8.conv.7
  # - features.9.conv.1
  # - features.9.conv.4
  # - features.9.conv.7
  # - features.10.conv.1
  # - features.10.conv.4
  # - features.10.conv.7
  # - features.11.conv.1
  # - features.11.conv.4
# features.11.conv.7
# features.12.conv.1
# features.12.conv.4
# features.12.conv.7
# features.13.conv.1
# features.13.conv.4
# features.13.conv.7
# features.14.conv.1
# features.14.conv.4
# features.14.conv.7
# features.15.conv.1
# features.15.conv.4
# features.15.conv.7
# features.16.conv.1
# features.16.conv.4
# features.16.conv.7
# features.17.conv.1
# features.17.conv.4
# features.17.conv.7
# features.18.1

resq_modules:
  - "features.0.2"
  - "features.1.conv.2"
  - "features.2.conv.2"
  - "features.2.conv.5"
  - "features.3.conv.2"
  - "features.3.conv.5"
  - "features.4.conv.2"
  - features.4.conv.5
  - features.5.conv.2
  - features.5.conv.5
  - features.6.conv.2
  - features.6.conv.5
  - features.7.conv.2
  - features.7.conv.5
  - features.8.conv.2
  - features.8.conv.5
  - features.9.conv.2
  - features.9.conv.5
  - features.10.conv.2
  - features.10.conv.5
  - features.11.conv.2
  - features.11.conv.5
  - features.12.conv.2
  - features.12.conv.5
  - features.13.conv.2
  - features.13.conv.5
  - features.14.conv.2
  - features.14.conv.5
  - features.15.conv.2
  - features.15.conv.5
  - features.16.conv.2
  - features.16.conv.5
  - features.17.conv.2
  - features.17.conv.5
  - features.18.2

